### ISSUE TITLE
Magic Fist Checklist

### ISSUE THREAD

**Issue by Shrooblord** [Shrooblord/raymap#8]
- [x] The ability to hold spacebar to charge, or tap spacebar to just shoot.
- [x] Charge particle FX and animations.
- [ ] Change current ALW_Rayman_projectile Perso-cloning logic to one more focussed on Particle FX and/or include a Particle FX child to the cloned Perso in order to properly manage things like particle tails and trails, on-hit additional particle sparkle spawning, etc..
- [ ] Shoot->Shoot->Shoot combo with proper animations.
- [ ] Shoot while running.
- [ ] Shoot->Jump in rapid succession with proper animations.
- [ ] Shoot while coming down from a jump.
- [ ] Shoot while jumping.
- [ ] Shoot while in Helico.
- [ ] Shoot while swimming.
- [ ] Shoot while sliding on slippery slope.
- [ ] Strafing; including shooting, combo-shooting, and charging.
- [ ] Missiles home in on targets and/or "directed" surface-bouncing behaviour.

**Comment by Shrooblord** [comment]
Moved to the repo it actually belongs in.

https://github.com/Shrooblord/RaymapGame/issues/1
